#!/bin/sh

COMMIT_TYPE="(feat|fix|refactor|docs|build|ci|style|test|revert)"

VALID_MESSAGE="feat: DMATH-123 Реализована отправка загружаемых файлов"

regex_pattern="^($COMMIT_TYPE: [[:alpha:]]+-[[:digit:]]+) .*"
commit_message=$(<"$1")

if [[ ! "$commit_message" =~ $regex_pattern ]]; then
    echo "Error: Invalid commit message format."
    echo "Your commit message: '$commit_message'"
    echo "Expected format: '$COMMIT_TYPE: {TASK_ID} DESCRIPTION'"
    echo "Example: $VALID_MESSAGE"
    exit 1
fi

exit 0